# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='pup_name',
            new_name='track_name',
        ),
        migrations.AddField(
            model_name='track',
            name='approve',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
