# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20171002_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('category', models.CharField(choices=[('Technical', 'tech'), ('Economy', 'eco'), ('Art', 'art')], max_length=200, verbose_name='Course Category')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('image', models.FileField(upload_to=b'', verbose_name='Course Thumbnail')),
                ('source', models.CharField(choices=[('udemy', 'udemy'), ('coursera', 'coursera'), ('udacity', 'udacity'), ('edx', 'edx')], max_length=200, verbose_name='MOOC')),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.Course'),
        ),
    ]
